// Copyright 2022 puzzlerightservice authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.14.0
// source: right.proto

package puzzlerightservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RightAction int32

const (
	RightAction_ACCESS RightAction = 0
	RightAction_CREATE RightAction = 1
	RightAction_UPDATE RightAction = 2
	RightAction_DELETE RightAction = 3
)

// Enum value maps for RightAction.
var (
	RightAction_name = map[int32]string{
		0: "ACCESS",
		1: "CREATE",
		2: "UPDATE",
		3: "DELETE",
	}
	RightAction_value = map[string]int32{
		"ACCESS": 0,
		"CREATE": 1,
		"UPDATE": 2,
		"DELETE": 3,
	}
)

func (x RightAction) Enum() *RightAction {
	p := new(RightAction)
	*p = x
	return p
}

func (x RightAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RightAction) Descriptor() protoreflect.EnumDescriptor {
	return file_right_proto_enumTypes[0].Descriptor()
}

func (RightAction) Type() protoreflect.EnumType {
	return &file_right_proto_enumTypes[0]
}

func (x RightAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RightAction.Descriptor instead.
func (RightAction) EnumDescriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{0}
}

type RightRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   uint64      `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ObjectId uint64      `protobuf:"varint,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Action   RightAction `protobuf:"varint,3,opt,name=action,proto3,enum=puzzlerightservice.RightAction" json:"action,omitempty"`
}

func (x *RightRequest) Reset() {
	*x = RightRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RightRequest) ProtoMessage() {}

func (x *RightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RightRequest.ProtoReflect.Descriptor instead.
func (*RightRequest) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{0}
}

func (x *RightRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RightRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *RightRequest) GetAction() RightAction {
	if x != nil {
		return x.Action
	}
	return RightAction_ACCESS
}

type RightResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authorized bool `protobuf:"varint,1,opt,name=authorized,proto3" json:"authorized,omitempty"`
}

func (x *RightResponse) Reset() {
	*x = RightResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RightResponse) ProtoMessage() {}

func (x *RightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RightResponse.ProtoReflect.Descriptor instead.
func (*RightResponse) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{1}
}

func (x *RightResponse) GetAuthorized() bool {
	if x != nil {
		return x.Authorized
	}
	return false
}

type ObjectIds struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
}

func (x *ObjectIds) Reset() {
	*x = ObjectIds{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectIds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectIds) ProtoMessage() {}

func (x *ObjectIds) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectIds.ProtoReflect.Descriptor instead.
func (*ObjectIds) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectIds) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Actions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []RightAction `protobuf:"varint,1,rep,packed,name=list,proto3,enum=puzzlerightservice.RightAction" json:"list,omitempty"`
}

func (x *Actions) Reset() {
	*x = Actions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Actions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actions) ProtoMessage() {}

func (x *Actions) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actions.ProtoReflect.Descriptor instead.
func (*Actions) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{3}
}

func (x *Actions) GetList() []RightAction {
	if x != nil {
		return x.List
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ObjectId uint64   `protobuf:"varint,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
	List     *Actions `protobuf:"bytes,3,opt,name=list,proto3" json:"list,omitempty"`
}

func (x *Role) Reset() {
	*x = Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{4}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

func (x *Role) GetList() *Actions {
	if x != nil {
		return x.List
	}
	return nil
}

type Roles struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List []*Role `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *Roles) Reset() {
	*x = Roles{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Roles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Roles) ProtoMessage() {}

func (x *Roles) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Roles.ProtoReflect.Descriptor instead.
func (*Roles) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{5}
}

func (x *Roles) GetList() []*Role {
	if x != nil {
		return x.List
	}
	return nil
}

type RoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ObjectId uint64 `protobuf:"varint,2,opt,name=objectId,proto3" json:"objectId,omitempty"`
}

func (x *RoleRequest) Reset() {
	*x = RoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleRequest) ProtoMessage() {}

func (x *RoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleRequest.ProtoReflect.Descriptor instead.
func (*RoleRequest) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{6}
}

func (x *RoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoleRequest) GetObjectId() uint64 {
	if x != nil {
		return x.ObjectId
	}
	return 0
}

type UserRight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId uint64         `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	List   []*RoleRequest `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
}

func (x *UserRight) Reset() {
	*x = UserRight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserRight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRight) ProtoMessage() {}

func (x *UserRight) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRight.ProtoReflect.Descriptor instead.
func (*UserRight) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{7}
}

func (x *UserRight) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserRight) GetList() []*RoleRequest {
	if x != nil {
		return x.List
	}
	return nil
}

type UserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UserId) Reset() {
	*x = UserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_right_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_right_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_right_proto_rawDescGZIP(), []int{8}
}

func (x *UserId) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_right_proto protoreflect.FileDescriptor

var file_right_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x72, 0x69, 0x67, 0x68, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x12, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x7b, 0x0a, 0x0c, 0x52, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x62, 0x6a,
	0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69,
	0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x69, 0x67, 0x68, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2f,
	0x0a, 0x0d, 0x52, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1e, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x22,
	0x1d, 0x0a, 0x09, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x52, 0x03, 0x69, 0x64, 0x73, 0x22, 0x3e,
	0x0a, 0x07, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x33, 0x0a, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x69, 0x67,
	0x68, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x67,
	0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67,
	0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x35, 0x0a, 0x05, 0x52, 0x6f, 0x6c, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x3d,
	0x0a, 0x0b, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x08, 0x6f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x22, 0x58, 0x0a,
	0x09, 0x55, 0x73, 0x65, 0x72, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x33, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1f, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x22, 0x18, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x49,
	0x64, 0x2a, 0x3d, 0x0a, 0x0b, 0x52, 0x69, 0x67, 0x68, 0x74, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x55, 0x50, 0x44, 0x41,
	0x54, 0x45, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x03,
	0x32, 0xce, 0x03, 0x0a, 0x05, 0x52, 0x69, 0x67, 0x68, 0x74, 0x12, 0x50, 0x0a, 0x09, 0x41, 0x75,
	0x74, 0x68, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65,
	0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x69, 0x67,
	0x68, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52,
	0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x09,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x70, 0x75, 0x7a, 0x7a,
	0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x4f,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x64, 0x73, 0x1a, 0x19, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c,
	0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f,
	0x6c, 0x65, 0x73, 0x12, 0x49, 0x0a, 0x09, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1f, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x4e,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1d, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x69, 0x67, 0x68, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x75,
	0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x52, 0x69, 0x67, 0x68, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49,
	0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x70,
	0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65, 0x1a, 0x21, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0d, 0x4c, 0x69, 0x73,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x1a, 0x2e, 0x70, 0x75, 0x7a,
	0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x19, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72,
	0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x73, 0x42, 0x65, 0x0a, 0x1f, 0x69, 0x6f, 0x2e, 0x64, 0x76, 0x61, 0x75, 0x6d, 0x6f, 0x72, 0x6f,
	0x6e, 0x2e, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68, 0x74, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x42, 0x17, 0x50, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x52, 0x69, 0x67, 0x68,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a,
	0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x76, 0x61, 0x75,
	0x6d, 0x6f, 0x72, 0x6f, 0x6e, 0x2f, 0x70, 0x75, 0x7a, 0x7a, 0x6c, 0x65, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_right_proto_rawDescOnce sync.Once
	file_right_proto_rawDescData = file_right_proto_rawDesc
)

func file_right_proto_rawDescGZIP() []byte {
	file_right_proto_rawDescOnce.Do(func() {
		file_right_proto_rawDescData = protoimpl.X.CompressGZIP(file_right_proto_rawDescData)
	})
	return file_right_proto_rawDescData
}

var file_right_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_right_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_right_proto_goTypes = []interface{}{
	(RightAction)(0),      // 0: puzzlerightservice.RightAction
	(*RightRequest)(nil),  // 1: puzzlerightservice.RightRequest
	(*RightResponse)(nil), // 2: puzzlerightservice.RightResponse
	(*ObjectIds)(nil),     // 3: puzzlerightservice.ObjectIds
	(*Actions)(nil),       // 4: puzzlerightservice.Actions
	(*Role)(nil),          // 5: puzzlerightservice.Role
	(*Roles)(nil),         // 6: puzzlerightservice.Roles
	(*RoleRequest)(nil),   // 7: puzzlerightservice.RoleRequest
	(*UserRight)(nil),     // 8: puzzlerightservice.UserRight
	(*UserId)(nil),        // 9: puzzlerightservice.UserId
}
var file_right_proto_depIdxs = []int32{
	0,  // 0: puzzlerightservice.RightRequest.action:type_name -> puzzlerightservice.RightAction
	0,  // 1: puzzlerightservice.Actions.list:type_name -> puzzlerightservice.RightAction
	4,  // 2: puzzlerightservice.Role.list:type_name -> puzzlerightservice.Actions
	5,  // 3: puzzlerightservice.Roles.list:type_name -> puzzlerightservice.Role
	7,  // 4: puzzlerightservice.UserRight.list:type_name -> puzzlerightservice.RoleRequest
	1,  // 5: puzzlerightservice.Right.AuthQuery:input_type -> puzzlerightservice.RightRequest
	3,  // 6: puzzlerightservice.Right.ListRoles:input_type -> puzzlerightservice.ObjectIds
	7,  // 7: puzzlerightservice.Right.RoleRight:input_type -> puzzlerightservice.RoleRequest
	8,  // 8: puzzlerightservice.Right.UpdateUser:input_type -> puzzlerightservice.UserRight
	5,  // 9: puzzlerightservice.Right.UpdateRole:input_type -> puzzlerightservice.Role
	9,  // 10: puzzlerightservice.Right.ListUserRoles:input_type -> puzzlerightservice.UserId
	2,  // 11: puzzlerightservice.Right.AuthQuery:output_type -> puzzlerightservice.RightResponse
	6,  // 12: puzzlerightservice.Right.ListRoles:output_type -> puzzlerightservice.Roles
	4,  // 13: puzzlerightservice.Right.RoleRight:output_type -> puzzlerightservice.Actions
	2,  // 14: puzzlerightservice.Right.UpdateUser:output_type -> puzzlerightservice.RightResponse
	2,  // 15: puzzlerightservice.Right.UpdateRole:output_type -> puzzlerightservice.RightResponse
	6,  // 16: puzzlerightservice.Right.ListUserRoles:output_type -> puzzlerightservice.Roles
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_right_proto_init() }
func file_right_proto_init() {
	if File_right_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_right_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RightRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RightResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectIds); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Actions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Roles); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserRight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_right_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_right_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_right_proto_goTypes,
		DependencyIndexes: file_right_proto_depIdxs,
		EnumInfos:         file_right_proto_enumTypes,
		MessageInfos:      file_right_proto_msgTypes,
	}.Build()
	File_right_proto = out.File
	file_right_proto_rawDesc = nil
	file_right_proto_goTypes = nil
	file_right_proto_depIdxs = nil
}
